apiVersion: v2
name: nebuly-platform
description: Helm chart for installing Nebuly's Platform on Kubernetes.

type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.34.1

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.0.0"

home: https://nebuly.com

sources:
  - https://github.com/nebuly-ai/helm-charts

dependencies:
  - name: strimzi-kafka-operator
    version: <=1.0.0
    repository: oci://quay.io/strimzi-helm
    condition: strimzi.enabled
  - name: altinity-clickhouse-operator
    version: ~0.24.4
    repository: https://docs.altinity.com/clickhouse-operator
    condition: clickhouse.enabled
  - name: bootstrap-aws
    version: ~0.3.0
    condition: bootstrap-aws.enabled
    repository: "file://../bootstrap-aws"
  - name: bootstrap-azure
    version: ~0.1.0
    condition: bootstrap-azure.enabled
    repository: "file://../bootstrap-azure"
  - name: bootstrap-gcp
    version: ~0.1.0
    condition: bootstrap-gcp.enabled
    repository: "file://../bootstrap-gcp"

maintainers:
  - name: Michele Zanotti
    email: m.zanotti@nebuly.ai
    url: https://github.com/Telemaco019
  - name: Diego Fiori
    email: d.fiori@nebuly.ai
    url: https://github.com/diegofiori
