apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: event-ingestion
spec:
  provider: azure
  parameters:
    # ID of the managed identity used for authenticating with the Key Vault.
    # Can be retrieved from the outputs of the Terraform module used for provisioning the k8s cluster (field "client_id")
    # $ terraform output aks_secrets_provider_managed_identity
    userAssignedIdentityID: "85ea93ac-dcfa-48c3-8ecd-b09d691124df"
    keyvaultName: "nbllabakskv"
    tenantId: "4e16af92-dd38-417c-bf9d-a24f891a7987"
    usePodIdentity: "false"
    useVMManagedIdentity: "true"

    objects: |
      array:
        - |
          objectName: nbllab-event-ingestion-auth0-client-id
          objectType: secret              
          objectVersion: ""
        - |
          objectName: nbllab-event-ingestion-auth0-client-secret
          objectType: secret              
          objectVersion: ""
        - |
          objectName: nbllabplatformhubns-connection-string          
          objectType: secret              
          objectVersion: ""

  secretObjects:
    - data:
        - key: oauth-client-id
          objectName: nbllab-event-ingestion-auth0-client-id
        - key: oauth-client-secret
          objectName: nbllab-event-ingestion-auth0-client-secret
        - key: eventhub-connection-string
          objectName: nbllabplatformhubns-connection-string
      secretName: event-ingestion-credentials
      type: Opaque
