apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: tenant-registry
spec:
  provider: azure
  parameters:
    # ID of the managed identity used for authenticating with the Key Vault.
    # Can be retrieved from the outputs of the Terraform module used for provisioning the k8s cluster (field "client_id")
    # $ terraform output aks_secrets_provider_managed_identity
    userAssignedIdentityID: "85ea93ac-dcfa-48c3-8ecd-b09d691124df"
    keyvaultName: "nbllabakskv"
    tenantId: "4e16af92-dd38-417c-bf9d-a24f891a7987"
    usePodIdentity: "false"
    useVMManagedIdentity: "true"

    objects: |
      array:
        - |
          objectName: nbllab-tenant-registry-dev-postgres-password
          objectType: secret              
          objectVersion: ""               
        - |
          objectName: nbllab-tenant-registry-dev-postgres-user
          objectType: secret              
          objectVersion: ""
        - | 
          objectName: nbllab-tenant-registry-azure-client-id
          objectType: secret              
          objectVersion: ""
        - | 
          objectName: nbllab-tenant-registry-azure-client-secret
          objectType: secret              
          objectVersion: ""

        - | 
          objectName: nbllab-stripe-nebuly-inc-webhook-secret
          objectType: secret              
          objectVersion: ""
        - | 
          objectName: nbllab-stripe-nebuly-inc-api-key
          objectType: secret              
          objectVersion: ""

        - | 
          objectName: nbllab-stripe-nebuly-srl-webhook-secret
          objectType: secret              
          objectVersion: ""
        - | 
          objectName: nbllab-stripe-nebuly-srl-api-key
          objectType: secret              
          objectVersion: ""
        - | 
          objectName: nbllab-admin-user-password
          objectType: secret              
          objectVersion: ""
        - | 
          objectName: nbllab-auth-jwt-key
          objectType: secret              
          objectVersion: ""
      
      
        - | 
          objectName: nbllab-microsoft-oauth-client-id
          objectType: secret              
          objectVersion: ""
        - | 
          objectName: nbllab-microsoft-oauth-client-secret
          objectType: secret              
          objectVersion: ""

  secretObjects:
    - data:
        - key: postgres-password
          objectName: nbllab-tenant-registry-dev-postgres-password
        - key: postgres-user
          objectName: nbllab-tenant-registry-dev-postgres-user
        - key: azure-client-id
          objectName: nbllab-tenant-registry-azure-client-id
        - key: azure-client-secret
          objectName: nbllab-tenant-registry-azure-client-secret

        - key: stripe-nebuly-srl-webhook-secret
          objectName: nbllab-stripe-nebuly-srl-webhook-secret
        - key: stripe-nebuly-srl-api-key
          objectName: nbllab-stripe-nebuly-srl-api-key

        - key: stripe-nebuly-inc-webhook-secret
          objectName: nbllab-stripe-nebuly-inc-webhook-secret
        - key: stripe-nebuly-inc-api-key
          objectName: nbllab-stripe-nebuly-inc-api-key

        - key: admin-user-password
          objectName: nbllab-admin-user-password
        - key: jwt-key
          objectName: nbllab-auth-jwt-key

        - key: microsoft-oauth-client-id
          objectName: nbllab-microsoft-oauth-client-id
        - key: microsoft-oauth-client-secret
          objectName: nbllab-microsoft-oauth-client-secret
      secretName: tenant-registry-credentials
      type: Opaque
