apiVersion: v1
kind: Service
metadata:
  name: {{ include "authService.fullname" . }}
  labels:
    {{- include "authService.labels" . | nindent 4 }}
spec:
  type: {{ .Values.auth.service.type }}
  ports:
    - port: {{ .Values.auth.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "authService.selectorLabels" . | nindent 4 }}
