apiVersion: v1
kind: Secret
metadata:
  name: {{ include "authService.fullname" . }}
  namespace: {{ include "nebuly-platform.namespace" . }}
  labels:
    {{- include "authService.labels" . | nindent 4 }}
  annotations:
    {{- include "nebuly-platform.annotations" . | nindent 4 }}
stringData:
  postgres-user: "{{ .Values.auth.postgresUser }}"
  postgres-password: "{{ .Values.auth.postgresPassword }}"
  azure-client-id: "{{ default "" .Values.secretsStore.azure.clientId }}"
  azure-client-secret: "{{ default "" .Values.secretsStore.azure.clientSecret }}"
  microsoft-oauth-tenant-id: "{{ default "" .Values.auth.microsoft.tenantId }}"
  microsoft-oauth-client-id: "{{ default "" .Values.auth.microsoft.clientId }}"
  microsoft-oauth-client-secret: "{{ default "" .Values.auth.microsoft.clientSecret }}"
  okta-oauth-client-id: "{{ default "" .Values.auth.okta.clientId }}"
  okta-oauth-client-secret: "{{ default "" .Values.auth.okta.clientSecret }}"
  ldap-admin-username: "{{ default "" .Values.auth.ldap.adminUsername }}"
  ldap-admin-password: "{{ default "" .Values.auth.ldap.adminPassword }}"
