apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
stringData:
  analytic-database-user: "{{ .Values.analyticDatabase.user }}"
  analytic-database-password: "{{ .Values.analyticDatabase.password }}"
  azure-openai-api-key: "{{ .Values.azureOpenAi.apiKey }}"
