apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
stringData:
  postgres-user: "{{ .Values.backend.postgresUser }}"
  postgres-password: "{{ .Values.backend.postgresPassword }}"
  analytic-database-user: "{{ .Values.analyticDatabase.user }}"
  analytic-database-password: "{{ .Values.analyticDatabase.password }}"
  oauth-client-id: "{{ .Values.backend.oauthClientId }}"
  oauth-client-secret: "{{ .Values.backend.oauthClientSecret }}"