apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}
  namespace: {{ include "nebuly-platform.namespace" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
  annotations:
    {{- include "nebuly-platform.annotations" . | nindent 4 }}
stringData:
  analytic-database-user: "{{ .Values.analyticDatabase.user }}"
  analytic-database-password: "{{ .Values.analyticDatabase.password }}"
  openai-api-key: "{{ .Values.openAi.apiKey }}"
