apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clickhouse.fullname" . }}
  namespace: {{ include "nebuly-platform.namespace" . }}
  labels:
    {{- include "nebuly-platform.selectorLabels" . | nindent 4 }}
  annotations:
    {{- include "nebuly-platform.annotations" . | nindent 4 }}
stringData:
  azure-storage-account-key: {{ .Values.clickhouse.backups.azure.storageAccountKey | quote }}

