apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "eventIngestion.fullname" . }}
  namespace: {{ include "nebuly-platform.namespace" . }}
  labels:
    {{- include "eventIngestion.labels" . | nindent 4 }}
  annotations:
    {{- include "nebuly-platform.annotations" . | nindent 4 }}
spec:
  replicas: {{ .Values.eventIngestion.replicaCount }}
  selector:
    matchLabels:
      {{- include "eventIngestion.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.eventIngestion.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "eventIngestion.labels" . | nindent 8 }}
        {{- with .Values.eventIngestion.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.eventIngestion.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.eventIngestion.securityContext | nindent 12 }}
          image: "{{ .Values.eventIngestion.image.repository }}:{{ .Values.eventIngestion.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.eventIngestion.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            # Kafka settings
            - name: "KAFKA_BOOTSTRAP_SERVERS"
              value: {{ include "kafka.bootstrapServers" . }}
            - name: "KAFKA_SASL_MECHANISM"
              value: {{ include "kafka.saslMechanism" . | quote }}
            - name: "KAFKA_SASL_PASSWORD"
              {{- include "kafka.saslPasswordEnv" . | nindent 14 }}
            - name: "KAFKA_SASL_USERNAME"
              {{- include "kafka.saslUsernameEnv" . | nindent 14 }}
            - name: "KAFKA_SOCKET_KEEPALIVE_ENABLED"
              value: {{ .Values.kafka.socketKeepAliveEnabled  | quote }}
            {{- if eq .Values.kafka.saslMechanism "GSSAPI" }}
            - name: "KAFKA_SASL_GSSAPI_SERVICE_NAME"
              value: {{ .Values.kafka.saslGssapiServiceName | quote }}
            - name: "KAFKA_SASL_GSSAPI_PRINCIPAL"
              value: {{ .Values.kafka.saslGssapiKerberosPrincipal | quote }}
            {{- end }}
            {{- if not .Values.kafka.external }}
            - name: "KAFKA_SSL_CA_PATH"
              value: "/etc/kafka/ca.crt"
            {{- end }}
            # Kafka topics
            - name: "KAFKA_TOPIC_EVENTS_MAIN"
              value: {{ .Values.kafka.topicEventsMain.name }}
            # Platform Services
            - name: "TENANT_REGISTRY_URL"
              value: {{ include "authService.url" . }}
            # OTEL
            - name: OTEL_ENABLED
              value: "{{ .Values.otel.enabled }}"
            - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
              value: "{{ .Values.otel.exporterOtlpTracesEndpoint }}"
            - name: OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
              value: "{{ .Values.otel.exporterOtlpMetricsEndpoint }}"
            - name: OTEL_METRICS_EXPORTER
              value: "otlp"
            - name: OTEL_SERVICE_NAME
              value: "nebuly-event-ingestion"
            # Sentry
            - name: SENTRY_ENABLED
              value: {{ .Values.eventIngestion.sentry.enabled | quote }}
            - name: SENTRY_ENVIRONMENT
              value: {{ .Values.eventIngestion.sentry.environment | quote }}
            - name: SENTRY_DSN
              value: {{ .Values.eventIngestion.sentry.dsn | quote }}
            - name: SENTRY_TRACES_SAMPLE_RATE
              value: {{ .Values.eventIngestion.sentry.tracesSampleRate | quote }}
            - name: SENTRY_PROFILES_SAMPLE_RATE
              value: {{ .Values.eventIngestion.sentry.profilesSampleRate | quote }}
            # Misc
            - name: "ENV"
              value: "prod"
            - name: "SERVER_PORT"
              value: "8080"
            - name: "FORWARDED_ALLOW_IPS"
              value: "*"
            - name: "PROJECT_NAME"
              value: "Event Ingestion"
            - name: "DEVELOPMENT_MODE"
              value: "false"
            {{- if .Values.eventIngestion.rootPath }}
            - name: "ROOT_PATH"
              value: {{ .Values.eventIngestion.rootPath }}
            {{- end }}

          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            {{- toYaml .Values.eventIngestion.resources | nindent 12 }}
          volumeMounts:
          {{- if not .Values.kafka.external }}
           - name: kafka-cluster-ca-cert
             mountPath: "/etc/kafka"
             readOnly: true
          {{- end }}
          {{- with .Values.eventIngestion.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
      {{- if not .Values.kafka.external }}
        - name: kafka-cluster-ca-cert
          secret:
            secretName: {{ include "kafka.fullname" . }}-cluster-ca-cert
      {{- end }}
      {{- with .Values.eventIngestion.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.eventIngestion.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.eventIngestion.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.eventIngestion.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
