apiVersion: v1
kind: Service
metadata:
  name: {{ include "eventIngestion.fullname" . }}
  namespace: {{ include "nebuly-platform.namespace" . }}
  labels:
    {{- include "eventIngestion.labels" . | nindent 4 }}
  annotations:
    {{- include "nebuly-platform.annotations" . | nindent 4 }}
spec:
  type: {{ .Values.eventIngestion.service.type }}
  ports:
    - port: {{ .Values.eventIngestion.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "eventIngestion.selectorLabels" . | nindent 4 }}
