apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ingestionWorker.fullname" . }}
  labels:
    {{- include "ingestionWorker.labels" . | nindent 4 }}
stringData:
  analytic-database-user: "{{ .Values.analyticDatabase.user }}"
  analytic-database-password: "{{ .Values.analyticDatabase.password }}"
  oauth-client-id: "{{ .Values.ingestionWorker.oauthClientId }}"
  oauth-client-secret: "{{ .Values.ingestionWorker.oauthClientSecret }}"
  openai-organization-id: "{{ .Values.openai.organizationId }}"
  openai-api-key: "{{ .Values.openai.apiKey }}"
  kafka-sasl-username: "{{ .Values.kafka.saslUsername }}"
  kafka-sasl-password: "{{ .Values.kafka.saslPassword }}"
