apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ingestionWorker.fullname" . }}
  labels:
    {{- include "ingestionWorker.labels" . | nindent 4 }}
stringData:
  analytic-database-user: "{{ .Values.analyticDatabase.user }}"
  analytic-database-password: "{{ .Values.analyticDatabase.password }}"
  kafka-sasl-username: "{{ .Values.kafka.saslUsername }}"
  kafka-sasl-password: "{{ .Values.kafka.saslPassword }}"
