apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ingestionWorker.fullname" . }}
  labels:
    {{- include "ingestionWorker.labels" . | nindent 4 }}
stringData:
  analytic-database-user: {{ .Values.analyticDatabase.user | quote }}
  analytic-database-password: {{ .Values.analyticDatabase.password | quote }}
  kafka-sasl-username: {{ .Values.kafka.saslUsername | quote }}
  kafka-sasl-password: {{ .Values.kafka.saslPassword | quote }}
  azureml-azure-client-id: {{ .Values.azureml.clientId | quote }}
  azureml-azure-client-secret: {{ .Values.azureml.clientSecret  | quote }}
