apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ingestionWorker.fullname" . }}
  labels:
    {{- include "ingestionWorker.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.ingestionWorker.replicaCount }}
  selector:
    matchLabels:
      {{- include "ingestionWorker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.ingestionWorker.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ingestionWorker.labels" . | nindent 8 }}
        {{- with .Values.ingestionWorker.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.ingestionWorker.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.ingestionWorker.securityContext | nindent 12 }}
          image: "{{ .Values.ingestionWorker.image.repository }}:{{ .Values.ingestionWorker.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.ingestionWorker.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.ingestionWorker.service.port }}
              protocol: TCP
          env:
            # Database
            - name: "POSTGRES_USER"
              valueFrom:
                secretKeyRef:
                  name: {{ include "ingestionWorker.fullname" . }}
                  key: analytic-database-user
            - name: "POSTGRES_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: {{ include "ingestionWorker.fullname" . }}
                  key: analytic-database-password
            # Kafka Settings
            - name: "KAFKA_SASL_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: {{ include "ingestionWorker.fullname" . }}
                  key: kafka-sasl-password
            - name: "KAFKA_SASL_USERNAME"
              valueFrom:
                secretKeyRef:
                  name: {{ include "ingestionWorker.fullname" . }}
                  key: kafka-sasl-username

          livenessProbe:
            exec:
              command:
                - python
                - app/health_check.py
                - "60" # max allowed stale seconds
            initialDelaySeconds: 5
            periodSeconds: 10

          resources:
            {{- toYaml .Values.ingestionWorker.resources | nindent 12 }}
          {{- with .Values.ingestionWorker.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.ingestionWorker.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ingestionWorker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ingestionWorker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ingestionWorker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
