apiVersion: v1
kind: Service
metadata:
  name: {{ include "ingestionWorker.fullname" . }}
  labels:
    {{- include "ingestionWorker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ingestionWorker.service.type }}
  ports:
    - port: {{ .Values.ingestionWorker.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ingestionWorker.selectorLabels" . | nindent 4 }}
