apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "jobTopicsClustering.fullname" . }}
  namespace: {{ include "nebuly-platform.namespace" . }}
  labels:
    {{- include "jobTopicsClustering.labels" . | nindent 4 }}
  annotations:
    {{- include "nebuly-platform.annotations" . | nindent 4 }}
spec:
  schedule: {{ .Values.ingestionWorker.topicsClustering.schedule | quote }}
  jobTemplate:
    metadata:
      labels:
        {{- include "jobTopicsClustering.labels" . | nindent 10 }}
    spec:
      backoffLimit: 0
      template:
        metadata:
          {{- with .Values.ingestionWorker.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 14 }}
          {{- end }}
          labels:
            {{- include "jobTopicsClustering.labels" . | nindent 14 }}
            {{- with .Values.ingestionWorker.podLabels }}
            {{- toYaml . | nindent 14 }}
            {{- end }}
        spec:
          serviceAccountName: {{ .Values.serviceAccount.name }}
          restartPolicy: Never
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 14 }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.ingestionWorker.podSecurityContext | nindent 12 }}
          containers:
            - name: {{ .Chart.Name }}
              securityContext:
                {{- toYaml .Values.ingestionWorker.securityContext | nindent 16 }}
              image: "{{ .Values.actionsProcessing.image.repository }}:{{ .Values.actionsProcessing.image.tag | default .Chart.AppVersion }}"
              command: [ "python", "jobs/process_categories.py" ]
              imagePullPolicy: {{ .Values.actionsProcessing.image.pullPolicy }}
              ports:
                - name: http
                  containerPort: {{ .Values.ingestionWorker.service.port }}
                  protocol: TCP
              env:
                {{ include "ingestionWorker.commonEnv" . | nindent 18 }}
                {{ include "lionLinguist.commonEnv" . | nindent 18 }}
              resources:
                {{- toYaml .Values.ingestionWorker.topicsClustering.resources | nindent 18 }}
              volumeMounts:
                - name: models-cache
                  mountPath: /var/cache/nebuly
              {{- with .Values.ingestionWorker.volumeMounts }}
                {{- toYaml . | nindent 16 }}
              {{- end }}
          volumes:
            - name: models-cache
              emptyDir: {}
          {{- with .Values.ingestionWorker.volumes }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.ingestionWorker.topicsClustering.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 14 }}
          {{- end }}
          {{- with .Values.ingestionWorker.topicsClustering.affinity }}
          affinity:
            {{- toYaml . | nindent 14 }}
          {{- end }}
          {{- with .Values.ingestionWorker.topicsClustering.tolerations }}
          tolerations:
            {{- toYaml . | nindent 14 }}
          {{- end }}
