{{- if not .Values.azureml.enabled }}
# PVC for caching AI Models used for inference.
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "ingestionWorker.modelsCache.name" . }}
  labels:
    {{- include "ingestionWorker.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.ingestionWorker.modelsCache.size }}
  storageClassName: {{ .Values.ingestionWorker.modelsCache.size }}
{{- end }}