apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ingestionWorker.fullname" . }}
  labels:
    {{- include "ingestionWorker.labels" . | nindent 4 }}
stringData:
  analytic-database-user: {{ .Values.analyticDatabase.user | quote }}
  analytic-database-password: {{ .Values.analyticDatabase.password | quote }}
  azureml-azure-client-id: {{ .Values.azureml.clientId | quote }}
  azureml-azure-client-secret: {{ .Values.azureml.clientSecret  | quote }}
  azure-openai-api-key: {{ .Values.openAi.apiKey | quote }}
