apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ingestionWorker.fullname" . }}
  labels:
    {{- include "ingestionWorker.labels" . | nindent 4 }}
data:
  # Misc
  ENV: "prod"
  DEVELOPMENT_MODE: "false"
  TOUCH_EVERY_SECONDS: "10"
  # Sentry
  SENTRY_ENABLED: "false"
  # Workers
  NUMBER_OF_WORKERS_ACTIONS: {{ .Values.ingestionWorker.numWorkersActions | quote }}
  NUMBER_OF_WORKERS_INTERACTIONS: {{ .Values.ingestionWorker.numWorkersInteractions | quote }}
  NUMBER_OF_WORKERS_FEEDBACK_ACTIONS: {{ .Values.ingestionWorker.numWorkersFeedbackActions | quote }}
  # OTEL
  OTEL_SERVICE_NAME: "nebuly-ingestion-worker"
  OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: {{ .Values.otel.exporterOtlpTracesEndpoint | quote }}
  OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: {{ .Values.otel.exporterOtlpMetricsEndpoint | quote }}
  OTEL_ENABLED: {{ .Values.otel.enabled | quote}}
  OTEL_METRICS_EXPORTER: "otlp"
  # Postgres
  POSTGRES_DB: {{ .Values.analyticDatabase.name | quote }}
  POSTGRES_SERVER: {{ .Values.analyticDatabase.server | quote }}
  # Kafka Settings
  KAFKA_SASL_USERNAME: "$ConnectionString"
  KAFKA_SOCKET_KEEPALIVE_ENABLED: "true"
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.kafka.bootstrapServers | quote }}
  # Kafka Topics
  KAFKA_TOPIC_EVENTS_MAIN: {{ .Values.kafka.topicEventsMain | quote }}
  KAFKA_TOPIC_EVENTS_RETRY_1: {{ .Values.kafka.topicEventsRetry1 | quote }}
  KAFKA_TOPIC_EVENTS_RETRY_2: {{ .Values.kafka.topicEventsRetry2 | quote }}
  KAFKA_TOPIC_EVENTS_RETRY_3: {{ .Values.kafka.topicEventsRetry3 | quote }}
  KAFKA_TOPIC_EVENTS_DLQ: {{ .Values.kafka.topicEventsDlq | quote }}
  # Platform Services
  TENANT_REGISTRY_URL: "http://{{ include "tenantRegistry.fullname" . }}:{{ .Values.tenantRegistry.service.port }}"

