apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "jobActionsProcessing.fullname" . }}
  labels:
    {{- include "jobActionsProcessing.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.ingestionWorker.actionsProcessing.schedule | quote }}
  jobTemplate:
    metadata:
      labels:
        {{- include "jobActionsProcessing.labels" . | nindent 10 }}
    spec:
      backoffLimit: {{ .Values.ingestionWorker.actionsProcessing.backoffLimit }}
      template:
        metadata:
          {{- with .Values.ingestionWorker.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 14 }}
          {{- end }}
          labels:
            {{- include "jobActionsProcessing.labels" . | nindent 14 }}
            {{- with .Values.ingestionWorker.podLabels }}
            {{- toYaml . | nindent 14 }}
            {{- end }}
        spec:
          restartPolicy: Never
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 14 }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.ingestionWorker.podSecurityContext | nindent 12 }}
          containers:
            - name: {{ .Chart.Name }}
              securityContext:
                {{- toYaml .Values.ingestionWorker.securityContext | nindent 16 }}
              image: "{{ .Values.ingestionWorker.image.repository }}:{{ .Values.ingestionWorker.image.tag | default .Chart.AppVersion }}"
              command: [ "python", "jobs/process_actions.py" ]
              imagePullPolicy: {{ .Values.ingestionWorker.image.pullPolicy }}
              ports:
                - name: http
                  containerPort: {{ .Values.ingestionWorker.service.port }}
                  protocol: TCP
              env:
                {{ include "ingestionWorker.commonEnv" . | nindent 18 }}
              resources:
                {{- toYaml .Values.ingestionWorker.actionsProcessing.resources | nindent 18 }}
              {{- with .Values.ingestionWorker.volumeMounts }}
              volumeMounts:
                {{- toYaml . | nindent 18 }}
              {{- end }}
          {{- with .Values.ingestionWorker.volumes }}
          volumes:
            {{- toYaml . | nindent 14 }}
          {{- end }}
          {{- with .Values.ingestionWorker.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 14 }}
          {{- end }}
          {{- with .Values.ingestionWorker.affinity }}
          affinity:
            {{- toYaml . | nindent 14 }}
          {{- end }}
          {{- with .Values.ingestionWorker.tolerations }}
          tolerations:
            {{- toYaml . | nindent 14 }}
          {{- end }}
