apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ingestionWorker.fullname" . }}
  namespace: {{ include "nebuly-platform.namespace" . }}
  labels:
    {{- include "ingestionWorker.labels" . | nindent 4 }}
  annotations:
    {{- include "nebuly-platform.annotations" . | nindent 4 }}
spec:
  replicas: {{ .Values.ingestionWorker.replicaCount }}
  strategy:
    {{- .Values.ingestionWorker.deploymentStrategy | toYaml | nindent 4 }}
  selector:
    matchLabels:
      {{- include "ingestionWorker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.ingestionWorker.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ingestionWorker.labels" . | nindent 8 }}
        {{- with .Values.ingestionWorker.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.ingestionWorker.podSecurityContext | nindent 8 }}
      containers:
        # Container 1
        - name: "{{ .Chart.Name }}-1"
          securityContext:
            {{- toYaml .Values.ingestionWorker.securityContext | nindent 12 }}
          command:
            - python
            - entrypoints/entrypoint_1.py
          image: "{{ .Values.ingestionWorker.image.repository }}:{{ .Values.ingestionWorker.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.ingestionWorker.image.pullPolicy }}
          env:
            {{- include "ingestionWorker.commonEnv" . | nindent 12 }}
          livenessProbe:
            exec:
              command:
                - python
                - app/health_check.py
                - "60" # max allowed stale seconds
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            {{- toYaml .Values.ingestionWorker.stage1.resources | nindent 12 }}
          volumeMounts:
          {{- if not .Values.kafka.external }}
            - name: kafka-cluster-ca-cert
              mountPath: "/etc/kafka"
              readOnly: true
          {{- end }}
          {{- with .Values.ingestionWorker.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}

        # Container 2
        - name: "{{ .Chart.Name }}-2"
          securityContext:
            {{- toYaml .Values.ingestionWorker.securityContext | nindent 12 }}
          command:
            - python
            - entrypoints/entrypoint_2.py
          image: "{{ .Values.ingestionWorker.image.repository }}:{{ .Values.ingestionWorker.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.ingestionWorker.image.pullPolicy }}
          env:
            {{- include "ingestionWorker.commonEnv" . | nindent 12 }}
          livenessProbe:
            exec:
              command:
                - python
                - app/health_check.py
                - "60" # max allowed stale seconds
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            {{- toYaml .Values.ingestionWorker.stage2.resources | nindent 12 }}
          volumeMounts:
          {{- if not .Values.kafka.external }}
            - name: kafka-cluster-ca-cert
              mountPath: "/etc/kafka"
              readOnly: true
          {{- end }}
          {{- with .Values.ingestionWorker.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}

      volumes:
      {{- if not .Values.kafka.external }}
        - name: kafka-cluster-ca-cert
          secret:
            secretName: {{ include "kafka.fullname" . }}-cluster-ca-cert
      {{- end }}
      {{- with .Values.ingestionWorker.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ingestionWorker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ingestionWorker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ingestionWorker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

