{{- if .Values.kafka.external }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "externalKakfaSecretName" . }}
  namespace: {{ include "nebuly-platform.namespace" . }}
  labels:
    {{ include "nebuly-platform.selectorLabels" . | nindent 4 }}
  annotations:
    {{- include "nebuly-platform.annotations" . | nindent 4 }}
stringData:
  kafka-sasl-username: {{ .Values.kafka.saslUsername | quote }}
  kafka-sasl-password: {{ .Values.kafka.saslPassword | quote }}

{{- end -}}