{{ if not .Values.kafka.external -}}
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ include "kafka.fullname" . }}
  namespace: {{ include "nebuly-platform.namespace" . }}
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: {{ include "kafka.kraft" . }}
    {{- include "nebuly-platform.annotations" . | nindent 4 }}
spec:
  entityOperator:
    userOperator: {}
    topicOperator: {}
  kafka:
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: true
        authentication:
          type: scram-sha-512
    authorization:
      type: simple
    rack:
      {{- toYaml .Values.kafka.rack | nindent 6 }}
    config:
      {{- toYaml .Values.kafka.config | nindent 6 }}
  {{- end }}