{{- if .Values.lionLinguist.modelsCache.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "lionLinguist.fullname" . }}
  namespace: {{ include "nebuly-platform.namespace" . }}
  labels:
    {{- include "lionLinguist.labels" . | nindent 4 }}
  annotations:
    {{- include "nebuly-platform.annotations" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.lionLinguist.modelsCache.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.lionLinguist.modelsCache.size }}
  storageClassName: {{ .Values.lionLinguist.modelsCache.storageClassName }}
{{- end }}