kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "lionLinguist.fullname" . }}
  labels:
    {{- include "lionLinguist.fullname" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.lionLinguist.modelsCache.size }}
  storageClassName: {{ .Values.lionLinguist.modelsCache.size }}