apiVersion: v1
kind: Service
metadata:
  name: {{ include "lionLinguist.fullname" . }}
  labels:
    {{- include "lionLinguist.labels" . | nindent 4 }}
spec:
  type: {{ .Values.lionLinguist.service.type }}
  ports:
    - port: {{ .Values.lionLinguist.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "lionLinguist.selectorLabels" . | nindent 4 }}
