apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lionLinguist.fullname" . }}
  namespace: {{ include "nebuly-platform.namespace" . }}
  labels:
    {{- include "lionLinguist.labels" . | nindent 4 }}
  annotations:
    {{- include "nebuly-platform.annotations" . | nindent 4 }}
spec:
  replicas: {{ .Values.lionLinguist.replicaCount }}
  strategy:
    {{- .Values.lionLinguist.deploymentStrategy | toYaml | nindent 4 }}
  selector:
    matchLabels:
      {{- include "lionLinguist.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.lionLinguist.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "lionLinguist.labels" . | nindent 8 }}
        {{- with .Values.lionLinguist.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.lionLinguist.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.lionLinguist.securityContext | nindent 12 }}
          image: "{{ .Values.lionLinguist.image.repository }}:{{ .Values.lionLinguist.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.lionLinguist.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            # OTEL
            - name: OTEL_ENABLED
              value: {{ .Values.otel.enabled | quote }}
            - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
              value: {{ .Values.otel.exporterOtlpTracesEndpoint | quote }}
            - name: OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
              value: {{ .Values.otel.exporterOtlpMetricsEndpoint | quote }}
            - name: OTEL_METRICS_EXPORTER
              value: "otlp"
            - name: OTEL_SERVICE_NAME
              value: "lion-linguist"
            # Sentry
            - name: SENTRY_ENABLED
              value: {{ .Values.lionLinguist.sentry.enabled | quote }}
            - name: SENTRY_ENVIRONMENT
              value: {{ .Values.lionLinguist.sentry.environment | quote }}
            - name: SENTRY_DSN
              value: {{ .Values.lionLinguist.sentry.dsn | quote }}
            - name: SENTRY_TRACES_SAMPLE_RATE
              value: {{ .Values.lionLinguist.sentry.tracesSampleRate | quote }}
            - name: SENTRY_PROFILES_SAMPLE_RATE
              value: {{ .Values.lionLinguist.sentry.profilesSampleRate | quote }}
            # Misc
            - name: "ENV"
              value: "prod"
            - name: "SERVER_PORT"
              value: "8080"
            - name: "PROJECT_NAME"
              value: "Lion Linguist"
            - name: "DEVELOPMENT_MODE"
              value: "false"
            - name: "MAX_CONCURRENT_REQUESTS"
              value: {{ .Values.lionLinguist.maxConcurrentRequests | quote }}
            # Models
            - name: "MODEL_PROVIDER"
              value: {{ .Values.aiModels.registry | quote }}
            - name: MODELS_CACHE_DIR
              value: "/var/cache"
            - name: EMBEDDING_WARNING_MODEL_NAME
              value: {{ .Values.aiModels.modelEmbeddingWarnings.name | quote }}
            - name: EMBEDDING_WARNING_MODEL_VERSION
              value: {{ .Values.aiModels.modelEmbeddingWarnings.version | quote }}
            - name: EMBEDDING_INTENT_MODEL_NAME
              value: {{ .Values.aiModels.modelEmbeddingIntents.name | quote }}
            - name: EMBEDDING_INTENT_MODEL_VERSION
              value: {{ .Values.aiModels.modelEmbeddingIntents.version | quote }}
            - name: EMBEDDING_TOPIC_MODEL_NAME
              value: {{ .Values.aiModels.modelEmbeddingTopic.name | quote }}
            - name: EMBEDDING_TOPIC_MODEL_VERSION
              value: {{ .Values.aiModels.modelEmbeddingTopic.version | quote }}
            # HF Env vars
            - name: SENTENCE_TRANSFORMERS_HOME
              value: "/tmp/hf"
            - name: HF_HOME
              value: "/tmp/hf"
            {{- if eq .Values.aiModels.registry  "azure_ml" }}
              {{ include "aiModels.azureml.env" . | nindent 12 }}
            {{- end }}
            {{- if eq .Values.aiModels.registry  "azure_storage" }}
              {{ include "aiModels.azure_storage.env" . | nindent 12 }}
            {{- end }}
            {{- if eq .Values.aiModels.registry  "aws_s3" }}
              {{ include "aiModels.aws.env" . | nindent 12 }}
            {{- end }}
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 10
            timeoutSeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            timeoutSeconds: 15
            periodSeconds: 15
          startupProbe:
            httpGet:
              path: /healthz
              port: http
            periodSeconds: 10
            failureThreshold: 60
          resources:
            {{- toYaml .Values.lionLinguist.resources | nindent 12 }}
          volumeMounts:
            - name: models-cache
              mountPath: /var/cache
              readOnly: false
              {{- with .Values.lionLinguist.volumeMounts }}
                {{- toYaml . | nindent 12 }}
              {{- end }}
      volumes:
        - name: models-cache
      {{- if .Values.lionLinguist.modelsCache.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "lionLinguist.fullname" . }}
      {{- else }}
          emptyDir: { }
      {{- end }}
      {{- with .Values.lionLinguist.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.lionLinguist.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.lionLinguist.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.lionLinguist.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
