{{- if .Values.aiModels.sync.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "modelsSync.fullname" . }}
  namespace: {{ include "nebuly-platform.namespace" . }}
  labels:
    {{- include "modelsSync.labels" . | nindent 4 }}
  annotations:
    {{- include "nebuly-platform.annotations" . | nindent 4 }}
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-upgrade, post-install
    "helm.sh/hook-weight": "-3"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: 0
  template:
    metadata:
      {{- with .Values.aiModels.sync.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "modelsSync.labels" . | nindent 8 }}
        {{- with .Values.aiModels.sync.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.aiModels.sync.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.aiModels.sync.securityContext | nindent 12 }}
          image: "{{ .Values.aiModels.sync.image.repository }}:{{ .Values.aiModels.sync.image.tag | default .Chart.AppVersion }}"
          command:
            - models-sync
            - {{ .Values.aiModels.modelEmbeddingWarnings.name }}:{{ .Values.aiModels.modelEmbeddingWarnings.version }}
            - {{ .Values.aiModels.modelEmbeddingTopic.name }}:{{ .Values.aiModels.modelEmbeddingTopic.version }}
            - {{ .Values.aiModels.modelEmbeddingIntents.name }}:{{ .Values.aiModels.modelEmbeddingIntents.version }}
            - {{ .Values.aiModels.modelInferenceInteractions.name }}:{{ .Values.aiModels.modelInferenceInteractions.version }}
            - {{ .Values.aiModels.modelTopicClassifier.name }}:{{ .Values.aiModels.modelTopicClassifier.version }}
            - {{ .Values.aiModels.modelActionClassifier.name }}:{{ .Values.aiModels.modelActionClassifier.version }}
            - --target-registry
            - {{ .Values.aiModels.registry }}
          imagePullPolicy: {{ .Values.aiModels.sync.image.pullPolicy }}
          env:
            # -- Source registry
            - name: "SOURCE_AZURE_TENANT_ID"
              value: "4e16af92-dd38-417c-bf9d-a24f891a7987"
            - name: "SOURCE_AZURE_SUBSCRIPTION_ID"
              value: "3b2549d7-9a32-4c32-87f0-fdad07768838"
            - name: "SOURCE_AZUREML_RESOURCE_GROUP"
              value: "rg-ml-eastus-prod"
            - name: "SOURCE_AZUREML_WORKSPACE_NAME"
              value: "nblprd-aml-eastus"
            - name: "SOURCE_AZURE_CLIENT_ID"
              valueFrom:
                secretKeyRef:
                  name: {{ (tpl .Values.aiModels.sync.source.existingSecret.name . ) | default (include "modelsSync.fullname" .) }}
                  key: {{ .Values.aiModels.sync.source.existingSecret.clientIdKey | default "source-azure-client-id" }}
            - name: "SOURCE_AZURE_CLIENT_SECRET"
              valueFrom:
                secretKeyRef:
                  name: {{ (tpl .Values.aiModels.sync.source.existingSecret.name . ) | default (include "modelsSync.fullname" .) }}
                  key: {{ .Values.aiModels.sync.source.existingSecret.clientSecretKey | default "source-azure-client-secret" }}
            # -- Target registry
            {{- if eq .Values.aiModels.registry "azure_storage" }}
            - name: "AZURE_TENANT_ID"
              value: {{ .Values.aiModels.azure.tenantId | quote }}
            - name: "AZURE_CLIENT_ID"
              value: {{ .Values.aiModels.azure.managedIdentityClientId | quote }}
            - name: "AZURE_STORAGE_ACCOUNT_NAME"
              value: {{ .Values.aiModels.azure.storageAccountName | quote }}
            - name: "AZURE_STORAGE_CONTAINER_NAME"
              value: {{ .Values.aiModels.azure.storageContainerName | quote }}
            {{- end }}
            {{- if eq .Values.aiModels.registry "aws_s3" }}
            {{- include "aiModels.aws.env" . | nindent 12 }}
            {{- end }}
            {{- if eq .Values.aiModels.registry "gcp_bucket" }}
            {{- include "aiModels.gcp.env" . | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.aiModels.sync.resources | nindent 12 }}
          {{- with .Values.aiModels.sync.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 14 }}
          {{- end }}
      {{- with .Values.aiModels.sync.volumes }}
      volumes:
        {{- toYaml . | nindent 10 }}
      {{- end }}
      {{- with .Values.aiModels.sync.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 10 }}
      {{- end }}
      {{- with .Values.aiModels.sync.affinity }}
      affinity:
        {{- toYaml . | nindent 10 }}
      {{- end }}
      {{- with .Values.aiModels.sync.tolerations }}
      tolerations:
        {{- toYaml . | nindent 10 }}
      {{- end }}
{{- end }}
