apiVersion: v1
kind: Secret
metadata:
  name: {{ include "modelRegistry.fullname" . }}
  namespace: {{ include "nebuly-platform.namespace" . }}
  labels:
    {{- include "nebuly-platform.selectorLabels" . | nindent 4 }}
  annotations:
    {{- include "nebuly-platform.annotations" . | nindent 4 }}
stringData:
  azure-client-id: {{ .Values.aiModels.azureml.clientId | quote }}
  azure-client-secret: {{ .Values.aiModels.azureml.clientSecret | quote }}
