{{- if .Values.aiModels.sync.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "modelsSync.fullname" . }}
  namespace: {{ include "nebuly-platform.namespace" . }}
  labels:
    {{- include "modelsSync.fullname" . | nindent 4 }}
  annotations:
    {{- include "nebuly-platform.annotations" . | nindent 4 }}
stringData:
  source-azure-client-id: {{ .Values.aiModels.sync.source.clientId | quote }}
  source-azure-client-secret: {{ .Values.aiModels.sync.source.clientSecret | quote }}
{{- end }}