{{- if .Values.postUpgrade.refreshRoTables.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ printf "%s-%s" .Release.Name "refresh-ro-tables" | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "postUpgrade.refreshRoLabels" . | nindent 4 }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
  template:
    metadata:
      name: {{ printf "%s-%s" .Release.Name "refresh-ro-tables" | trunc 63 | trimSuffix "-" }}
      labels:
        {{- include "postUpgrade.refreshRoLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      securityContext:
        {{- toYaml .Values.backend.podSecurityContext | nindent 8 }}
      containers:
        - name: backend
          securityContext:
            {{- toYaml .Values.backend.securityContext | nindent 12 }}
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag | default .Chart.AppVersion }}"
          command:
            - python
            - scripts/db_refresh.py
          resources:
            {{- toYaml .Values.postUpgrade.refreshRoTables.resources | nindent 12 }}
          env:
            {{- include "backend.commonEnv" . | nindent 12 }}
          {{- with .Values.backend.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.backend.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}