apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "jobProcessModelSuggestions.fullname" . }}
  namespace: {{ include "nebuly-platform.namespace" . }}
  labels:
    {{- include "jobProcessModelSuggestions.labels" . | nindent 4 }}
  annotations:
    {{- include "nebuly-platform.annotations" . | nindent 4 }}
spec:
  schedule: {{ .Values.primaryProcessing.schedule | quote }}
  jobTemplate:
    metadata:
      labels:
        {{- include "jobProcessModelSuggestions.labels" . | nindent 10 }}
    spec:
      backoffLimit: {{ .Values.primaryProcessing.backoffLimit }}
      template:
        metadata:
          {{- with .Values.primaryProcessing.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 14 }}
          {{- end }}
          labels:
            {{- include "jobProcessModelSuggestions.labels" . | nindent 14 }}
            {{- with .Values.primaryProcessing.podLabels }}
            {{- toYaml . | nindent 14 }}
            {{- end }}
        spec:
          hostIPC: {{ .Values.primaryProcessing.hostIPC }}
          serviceAccountName: {{ .Values.serviceAccount.name }}
          restartPolicy: Never
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 14 }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.primaryProcessing.podSecurityContext | nindent 12 }}
          containers:
            - name: {{ .Chart.Name }}
              securityContext:
                {{- toYaml .Values.primaryProcessing.securityContext | nindent 16 }}
              image: "{{ .Values.primaryProcessing.image.repository }}:{{ .Values.primaryProcessing.image.tag | default .Chart.AppVersion }}"
              command: [ "python", "jobs/process_model_suggestions.py" ]
              imagePullPolicy: {{ .Values.primaryProcessing.image.pullPolicy }}
              env:
                - name: MODEL_NAME
                  value: {{ .Values.aiModels.modelInferenceInteractions.name | quote }}
                - name: MODEL_VERSION
                  value: {{ .Values.aiModels.modelInferenceInteractions.version | quote }}
                # Model Suggestions Settings
                - name: MODEL_ISSUE_MAX_DATA
                  value: "5000"
                - name: MODEL_ISSUE_MAX_TOPICS
                  value: "200"
                - name: MODEL_ISSUE_MAX_LLM_ISSUES_GENERATION_ITERATIONS
                  value: "10"
                - name: MODEL_ISSUE_ASYNC_BATCH_SIZE
                  value: "40"
                - name: MODEL_ISSUE_LOCAL_MODEL_NAME
                  value: "model-issues-classifier"
                - name: MODEL_ISSUE_LOCAL_MODEL_VERSION
                  value: "2"
                - name: MODEL_ISSUE_LOCAL_MODEL_TEMPERATURE
                  value: "0.5"
                - name: MODEL_ISSUE_LOCAL_MODEL_GENERATIONS
                  value: "3"
                - name: MODEL_ISSUE_CLASSIFIER_KIND
                  value: "local_model_majority_vote"
                - name: MODEL_ISSUE_VARIABLE_CLASSIFIER
                  value: "false"
              {{ include "ingestionWorker.commonEnv" . | nindent 16 }}
              {{ include "batchJobs.commonEnv" . | nindent 16 }}
              {{ include "lionLinguist.commonEnv" . | nindent 16 }}
              {{- if eq .Values.aiModels.registry  "azure_ml" }}
                {{ include "aiModels.azureml.env" . | nindent 16 }}
              {{- end }}
              {{- if eq .Values.aiModels.registry  "azure_storage" }}
                {{ include "aiModels.azure_storage.env" . | nindent 16 }}
              {{- end }}
              {{- if eq .Values.aiModels.registry  "aws_s3" }}
                {{ include "aiModels.aws.env" . | nindent 16 }}
              {{- end }}
              {{- if eq .Values.aiModels.registry  "gcp_bucket" }}
                {{ include "aiModels.gcp.env" . | nindent 16 }}
              {{- end }}
              resources:
                {{- toYaml .Values.primaryProcessing.resources | nindent 18 }}
              volumeMounts:
                - name: vllm-report-usage
                  mountPath: /nonexistent
              {{- if not .Values.kafka.external }}
                - name: kafka-cluster-ca-cert
                  mountPath: "/etc/kafka"
                  readOnly: true
              {{- end }}
                - name: models-cache
                  mountPath: /var/cache/nebuly
                  readOnly: false
              {{- with .Values.primaryProcessing.volumeMounts }}
                {{- toYaml . | nindent 18 }}
              {{- end }}
          volumes:
            - name: vllm-report-usage
              emptyDir: {}
          {{- if not .Values.kafka.external }}
            - name: kafka-cluster-ca-cert
              secret:
                secretName: {{ include "kafka.fullname" . }}-cluster-ca-cert
          {{- end }}
            - name: models-cache
          {{- if .Values.primaryProcessing.modelsCache.enabled }}
              persistentVolumeClaim:
                claimName: {{ include "ingestionWorker.fullname" . }}
          {{- else }}
              emptyDir: { }
          {{- end }}
          {{- with .Values.primaryProcessing.volumes }}
            {{- toYaml . | nindent 14 }}
          {{- end }}
          {{- with .Values.primaryProcessing.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 14 }}
          {{- end }}
          {{- with .Values.primaryProcessing.affinity }}
          affinity:
            {{- toYaml . | nindent 14 }}
          {{- end }}
          {{- with .Values.primaryProcessing.tolerations }}
          tolerations:
            {{- toYaml . | nindent 14 }}
          {{- end }}
