{{ if .Values.telemetry.promtail.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "promtail.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "promtail.labels" . }}
data:
  promtail.yaml: {{ include "promtail.config" . | quote }}
{{- end }}