
{{ if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.fullname" . }}
  namespace: {{ include "nebuly-platform.namespace" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
  annotations:
    {{- include "nebuly-platform.annotations" . | nindent 4 }}
spec:
  selector:
    {{- include "redis.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: {{ .Values.redis.service.port }}
      protocol: TCP
      name: redis
{{- end }}