{{ if .Values.redis.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redis.fullname" . }}
  namespace: {{ include "nebuly-platform.namespace" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
  annotations:
    {{- include "nebuly-platform.annotations" . | nindent 4 }}
stringData:
  redis-password: {{ .Values.redis.auth.password | quote }}
{{- end }}

