{{- if and .Values.remoteAccess.enabled .Values.remoteAccess.apiToken }}
apiVersion: v1
kind: Secret
metadata:
  name: nebuly-remote-access
  namespace: {{ include "nebuly-platform.namespace" . }}
  annotations:
    {{- include "nebuly-platform.annotations" . | nindent 4 }}
type: Opaque
stringData:
  api-token: {{ .Values.remoteAccess.apiToken | quote }}
{{- end }}
