apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "jobProcessTopicsAndActions.fullname" . }}
  namespace: {{ include "nebuly-platform.namespace" . }}
  labels:
    {{- include "jobProcessTopicsAndActions.labels" . | nindent 4 }}
  annotations:
    {{- include "nebuly-platform.annotations" . | nindent 4 }}
spec:
  schedule: {{ .Values.secondaryProcessing.schedule | quote }}
  jobTemplate:
    metadata:
      labels:
        {{- include "jobProcessTopicsAndActions.labels" . | nindent 10 }}
    spec:
      backoffLimit: 0
      template:
        metadata:
          {{- with .Values.secondaryProcessing.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 14 }}
          {{- end }}
          labels:
            {{- include "jobProcessTopicsAndActions.labels" . | nindent 14 }}
            {{- with .Values.secondaryProcessing.podLabels }}
            {{- toYaml . | nindent 14 }}
            {{- end }}
        spec:
          hostIPC: {{ .Values.primaryProcessing.hostIPC }}
          serviceAccountName: {{ .Values.serviceAccount.name }}
          restartPolicy: Never
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 14 }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.secondaryProcessing.podSecurityContext | nindent 12 }}
          containers:
            - name: {{ .Chart.Name }}
              securityContext:
                {{- toYaml .Values.secondaryProcessing.securityContext | nindent 16 }}
              image: "{{ .Values.primaryProcessing.image.repository }}:{{ .Values.primaryProcessing.image.tag | default .Chart.AppVersion }}"
              command: [ "python", "jobs/process_topics_and_actions.py" ]
              imagePullPolicy: {{ .Values.primaryProcessing.image.pullPolicy }}
              env:
                {{ include "ingestionWorker.commonEnv" . | nindent 16 }}
                {{ include "lionLinguist.commonEnv" . | nindent 16 }}
                {{ include "batchJobs.commonEnv" . | nindent 16 }}
              resources:
                {{- toYaml .Values.primaryProcessing.resources | nindent 16 }}
              volumeMounts:
                - name: models-cache
                  mountPath: /var/cache/nebuly
              {{- with .Values.primaryProcessing.volumeMounts }}
                {{- toYaml . | nindent 16 }}
              {{- end }}
          volumes:
            - name: models-cache
              emptyDir: {}
          {{- with .Values.primaryProcessing.volumes }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.primaryProcessing.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 14 }}
          {{- end }}
          {{- with .Values.primaryProcessing.affinity }}
          affinity:
            {{- toYaml . | nindent 14 }}
          {{- end }}
          {{- with .Values.primaryProcessing.tolerations }}
          tolerations:
            {{- toYaml . | nindent 14 }}
          {{- end }}
