{{ if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ include "nebuly-platform.namespace" . }}
  labels:
    {{ include "nebuly-platform.labels" . | nindent 4 }}
  annotations:
    {{- include "nebuly-platform.annotations" . | nindent 4 }}
    {{ .Values.serviceAccount.annotations | toYaml | nindent 4 }}
{{- end }}