{{- if and .Values.telemetry.tenant .Values.telemetry.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: nebuly-telemetry
  namespace: {{ include "nebuly-platform.namespace" . }}
  annotations:
    {{- include "nebuly-platform.annotations" . | nindent 4 }}
type: Opaque
stringData:
  telemetry-tenant: {{ .Values.telemetry.tenant | quote }}
  telemetry-api-key: {{ .Values.telemetry.apiKey | quote }}
  telemetry-alertmanager-url: {{ printf "https://%s:%s@alertmanager.monitor.nebuly.com" .Values.telemetry.tenant .Values.telemetry.apiKey | quote }}
{{- end }}